# Generated by Django 4.0 on 2022-01-01 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='league',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='im.event'),
            preserve_default=False,
        ),
    ]
