# Generated by Django 4.0 on 2022-01-01 17:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_organization'),
        ('im', '0002_remove_eventregistration_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.OneToOneField(default=1, help_text='This user is able to manage the organization', on_delete=django.db.models.deletion.RESTRICT, related_name='org_owner', to='core.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='url_name',
            field=models.CharField(help_text='Link for your organization. Example input: ut_austin -> /org/ut_austin', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Alphabetic characters and underscores only.', regex='^[a-zA-Z_]*$')], verbose_name='URL Name'),
        ),
    ]
