# Generated by Django 4.0 on 2022-01-01 17:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0003_organization_owner_alter_organization_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='im.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='url_name',
            field=models.CharField(help_text='WARNING: THIS FIELD MAY NOT BE CHANGED AFTER CREATION. This field controls the URL your users will see. Example input: ut_austin -> /org/ut_austin/...', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Alphabetic characters and underscores only.', regex='^[a-zA-Z_]*$')], verbose_name='URL Name'),
        ),
    ]
